export const PROJECT_IDENTIFIER_MIN_LENGTH = 2
export const PROJECT_IDENTIFIER_MAX_LENGTH = 22
export const APPLICATION_IDENTIFIER_MIN_LENGTH = 2
export const APPLICATION_IDENTIFIER_MAX_LENGTH = 22
export const STAGE_IDENTIFIER_MAX_LENGTH = 12
