DROP FUNCTION IF EXISTS ai.release_run_lease(text, text);
DROP FUNCTION IF EXISTS ai.renew_run_lease(text, text, integer);
DROP FUNCTION IF EXISTS ai.claim_next_run(text, integer);
DROP TABLE IF EXISTS ai.idempotency_keys;
DROP TABLE IF EXISTS ai.tool_calls;
DROP TABLE IF EXISTS ai.run_events;
DROP TABLE IF EXISTS ai.items;
DROP TABLE IF EXISTS ai.runs;
DROP TABLE IF EXISTS ai.turns;
DROP TABLE IF EXISTS ai.conversations;
DROP SCHEMA IF EXISTS ai;
