-- Remove only objects owned by the version 103 Luna DevOps baseline.
-- RESTRICT is intentional: rollback must fail rather than delete objects that
-- another schema owner added with dependencies on Luna DevOps tables.

DROP TABLE IF EXISTS
    ai.conversation_summaries,
    ai.conversations,
    ai.idempotency_keys,
    ai.items,
    ai.model_credit_holds,
    ai.model_usages,
    ai.run_events,
    ai.runs,
    ai.tool_calls,
    ai.turns,
    public.access_tokens,
    public.ai_models,
    public.app_configs,
    public.app_template_installations,
    public.applications,
    public.artifact_registries,
    public.audit_logs,
    public.auth_admission_policies,
    public.auth_providers,
    public.auth_registration_settings,
    public.billing_ledger_entries,
    public.billing_rate_rules,
    public.billing_usage_records,
    public.build_environment_configs,
    public.build_jobs,
    public.build_logs,
    public.build_runs,
    public.build_variable_sets,
    public.container_images,
    public.deployment_target_hook_bindings,
    public.deployment_targets,
    public.deployment_volume_mounts,
    public.email_registration_challenges,
    public.external_identities,
    public.gateway_routes,
    public.git_accounts,
    public.git_providers,
    public.hook_run_logs,
    public.hook_runs,
    public.inbox_action_requests,
    public.inbox_messages,
    public.notification_channels,
    public.notification_deliveries,
    public.notification_rules,
    public.notification_templates,
    public.oauth_applications,
    public.oauth_authorization_codes,
    public.oauth_device_authorizations,
    public.oauth_grants,
    public.oauth_refresh_tokens,
    public.platform_events,
    public.platform_mail_settings,
    public.project_hook_configs,
    public.project_members,
    public.project_pins,
    public.project_runtime_config_sets,
    public.project_topology_edges,
    public.project_volume_quota_reservations,
    public.project_volume_quota_usage,
    public.project_volumes,
    public.projects,
    public.registry_credentials,
    public.release_logs,
    public.releases,
    public.repository_bindings,
    public.retained_volumes,
    public.runtime_clusters,
    public.runtime_observations,
    public.scoped_resource_project_bindings,
    public.secret_values,
    public.service_bindings,
    public.system_component_installations,
    public.user_notification_preferences,
    public.user_remember_tokens,
    public.user_sessions,
    public.user_wallets,
    public.users,
    public.volume_transfers;

DROP FUNCTION IF EXISTS public.luna_sync_project_volume_quota();
DROP FUNCTION IF EXISTS public.luna_project_volume_quota_limit_bytes();

DROP SCHEMA IF EXISTS ai;
