apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "luna-devops.sharedConfigName" . }}
  labels:
    {{- include "luna-devops.labels" . | nindent 4 }}
data:
  PUBLIC_BASE_URL: {{ .Values.app.publicBaseUrl | quote }}
  VOLUME_TRANSFER_MAX_BYTES: {{ .Values.volumeTransfer.maxBytes | quote }}
  VOLUME_TRANSFER_JOB_IMAGE: {{ include "luna-devops.volumeTransferJobImage" . | quote }}
