import type { TFunction } from 'i18next'

const actionPrefixes = [
  'acknowledge',
  'reconfigure',
  'regenerate',
  'initialize',
  'authorize',
  'complete',
  'exchange',
  'exec',
  'install',
  'preview',
  'refresh',
  'restart',
  'rollback',
  'search',
  'stream',
  'trigger',
  'cleanup',
  'create',
  'decide',
  'delete',
  'disable',
  'execute',
  'export',
  'receive',
  'resume',
  'revoke',
  'submit',
  'unbind',
  'update',
  'verify',
  'cancel',
  'check',
  'confirm',
  'enroll',
  'list',
  'read',
  'retry',
  'rotate',
  'start',
  'test',
  'get',
  'pin',
  'unpin',
] as const

const resourceAliases: Record<string, string> = {
  dashboard: 'dashboard',
  projects: 'projects',
  project: 'project',
  projectPins: 'projectPins',
  projectMembers: 'projectMembers',
  projectMember: 'projectMember',
  projectTopology: 'projectTopology',
  projectTopologyEdges: 'projectTopologyEdges',
  projectTopologyEdge: 'projectTopologyEdge',
  projectRuntimeConfigSets: 'runtimeConfigSets',
  projectRuntimeConfigSet: 'runtimeConfigSet',
  projectHookConfigs: 'hookConfigs',
  projectHookConfig: 'hookConfig',
  projectHookRuns: 'hookRuns',
  projectHookRunLog: 'hookRunLog',
  applications: 'applications',
  application: 'application',
  applicationTopology: 'applicationTopology',
  appTemplates: 'appTemplates',
  appTemplate: 'appTemplate',
  systemAppTemplate: 'systemAppTemplate',
  deploymentTargets: 'deploymentTargets',
  deploymentTarget: 'deploymentTarget',
  deploymentTargetData: 'deploymentData',
  deploymentTargetMetrics: 'deploymentMetrics',
  releases: 'releases',
  release: 'release',
  releaseLogs: 'releaseLogs',
  releaseRuntimeLogs: 'runtimeLogs',
  releaseRuntimeCommand: 'runtimeCommand',
  releaseRuntimeTerminal: 'runtimeTerminal',
  releaseImageCandidates: 'imageCandidates',
  runtimeClusters: 'runtimeClusters',
  runtimeCluster: 'runtimeCluster',
  runtimeClusterResources: 'runtimeResources',
  runtimeClusterResource: 'runtimeResource',
  runtimeClusterResourceYAML: 'runtimeResourceYAML',
  runtimeClusterResourceEvents: 'runtimeEvents',
  runtimeClusterPodTerminal: 'runtimeTerminal',
  gitProviders: 'gitProviders',
  gitProvider: 'gitProvider',
  gitAccounts: 'gitAccounts',
  gitAccount: 'gitAccount',
  gitRepositories: 'gitRepositories',
  gitRepositoryBuildOptions: 'repositoryBuildOptions',
  gitBranches: 'gitBranches',
  gitContents: 'gitContents',
  gitFile: 'gitFile',
  gitOAuth: 'gitAuthorization',
  gitWebhook: 'gitWebhook',
  repositoryBindings: 'repositoryBindings',
  repositoryBinding: 'repositoryBinding',
  repositoryWebhook: 'repositoryWebhook',
  artifactRegistries: 'artifactRegistries',
  artifactRegistry: 'artifactRegistry',
  registryCredentials: 'registryCredentials',
  allRegistryCredentials: 'registryCredentials',
  registryCredential: 'registryCredential',
  registryRepositories: 'registryRepositories',
  registryRepositoryTags: 'registryTags',
  registryImageTemplateDefault: 'registryTemplate',
  defaultArtifactRegistry: 'defaultArtifactRegistry',
  containerImages: 'containerImages',
  containerImage: 'containerImage',
  buildTemplates: 'buildTemplates',
  buildTemplate: 'buildTemplate',
  buildEnvironmentConfig: 'buildEnvironment',
  buildVariableSets: 'buildVariableSets',
  buildVariableSet: 'buildVariableSet',
  buildRuns: 'buildRuns',
  buildRun: 'buildRun',
  buildJobs: 'buildJobs',
  buildJob: 'buildJob',
  buildJobLogs: 'buildLogs',
  gatewayRoutes: 'gatewayRoutes',
  gatewayRoute: 'gatewayRoute',
  gatewayCertificates: 'gatewayCertificates',
  gatewayDomain: 'gatewayDomain',
  gatewayTrafficStatus: 'gatewayTraffic',
  serviceBindings: 'serviceBindings',
  serviceBinding: 'serviceBinding',
  notificationPresets: 'notificationPresets',
  notificationChannels: 'notificationChannels',
  notificationChannel: 'notificationChannel',
  notificationChannelFromPreset: 'notificationChannel',
  notificationTemplates: 'notificationTemplates',
  notificationTemplate: 'notificationTemplate',
  notificationRules: 'notificationRules',
  notificationRule: 'notificationRule',
  notificationDeliveries: 'notificationDeliveries',
  platformEvents: 'platformEvents',
  platformEvent: 'platformEvent',
  platformEventCatalog: 'eventCatalog',
  systemComponents: 'systemComponents',
  users: 'users',
  user: 'user',
  currentUser: 'currentUser',
  projectMemberCandidates: 'projectMemberCandidates',
  authProviders: 'authProviders',
  authProvider: 'authProvider',
  accessTokens: 'accessTokens',
  accessToken: 'accessToken',
  accessTokenScopes: 'accessTokenScopes',
  oauthApplications: 'oauthApplications',
  oauthApplication: 'oauthApplication',
  myOAuthGrants: 'oauthGrants',
  myOAuthGrant: 'oauthGrant',
  billingSummary: 'billingSummary',
  billingDeploymentSpend: 'deploymentSpend',
  billingLedgerEntries: 'billingLedger',
  billingUsageRecords: 'billingUsage',
  billingRateRules: 'billingRates',
  billingWalletTransaction: 'walletTransaction',
  externalBillingTransaction: 'externalBillingTransaction',
  projectOrder: 'projectOrder',
  configs: 'configs',
  configDefinitions: 'configDefinitions',
  dataRetentionCatalog: 'dataRetention',
  dataRetention: 'dataRetention',
  aiCapabilities: 'aiCapabilities',
  aiConversations: 'aiConversations',
  aiConversation: 'aiConversation',
  aiConversationTimeline: 'aiTimeline',
  aiRuns: 'aiRuns',
  aiRun: 'aiRun',
  aiRunEvents: 'aiRunEvents',
  aiRunInput: 'aiRunInput',
  aiToolApproval: 'aiToolApproval',
  aiTurn: 'aiTurn',
  pendingAIUIActions: 'aiUIActions',
  aiUIAction: 'aiUIAction',
  aiRunActorGrant: 'aiRunActorGrant',
  aiRunAfterMFA: 'aiRun',
  registeredAITool: 'registeredAITool',
  internalAIProviderConfig: 'aiProviderConfig',
  aiProviderConnection: 'aiProviderConnection',
  webPage: 'webPage',
  web: 'web',
}

const exactNames: Record<string, string> = {
  webSearch: 'webSearch',
  fetchWebPage: 'fetchWebPage',
  create_options: 'createOptions',
  prepare_interaction_cards: 'prepareInteractionCards',
  create_interaction_cards: 'createInteractionCards',
  navigate_to_route: 'navigateToRoute',
  rename_conversation: 'renameConversation',
}

export function toolDisplayName(t: TFunction, operationId: string): string {
  const exactName = exactNames[operationId]
  if (exactName)
    return t(`aiAssistant.tools.names.${exactName}`)

  const action = actionPrefixes.find(prefix => operationId.startsWith(prefix) && operationId.length > prefix.length)
  if (!action)
    return t('aiAssistant.tools.platformOperation')

  const rawResource = lowerFirst(operationId.slice(action.length))
  const resource = resourceAliases[rawResource]
  if (!resource)
    return t('aiAssistant.tools.platformOperation')

  return t('aiAssistant.tools.operationName', {
    action: t(`aiAssistant.tools.actions.${action}`),
    resource: t(`aiAssistant.tools.resources.${resource}`),
  })
}

function lowerFirst(value: string): string {
  for (const acronym of ['OAuth', 'OIDC', 'MFA', 'API', 'AI']) {
    if (value.startsWith(acronym))
      return `${acronym.toLowerCase()}${value.slice(acronym.length)}`
  }
  return value ? `${value[0].toLowerCase()}${value.slice(1)}` : value
}
