const appTemplatesPage = {
  description: 'Install databases, caches, observability tools, developer tools, and lightweight collaboration apps from presets.',
  heroEyebrow: 'Luna DevOps template library',
  heroTitle: 'Discover services. Deploy faster.',
  templateCount: 'Templates',
  categoryCount: 'Categories',
  browseTitle: 'Browse all templates',
  resultCount: '{{count}} templates available',
  searchPlaceholder: 'Search apps, use cases, or images',
  categoryFilter: 'Category Filter',
  allCategories: 'All Categories',
  sortBy: 'Sort Field',
  sortByPopularity: 'Popularity',
  sortByName: 'Name A-Z',
  sortOrder: 'Sort Order',
  sortDesc: 'Descending',
  sortAsc: 'Ascending',
  loading: 'Loading app templates...',
  emptyTitle: 'No templates found',
  emptyDescription: 'Try another keyword, or wait for administrators to add more templates.',
  install: 'Install',
  installing: 'Installing...',
  installStarted: 'App template installation started',
  systemInstallStarted: 'Platform component installation started',
  installDialogTitle: 'Install {{name}}',
  installDialogDescription: 'The template creates an application and deployment target in the selected project space. Secret values are stored securely and are not echoed back.',
  systemInstallDialogDescription: 'Platform components are installed into the system namespace of a runtime cluster to extend platform capabilities. They do not create project-space applications.',
  platformComponent: 'Platform Component',
  selectRuntimeCluster: 'Select runtime cluster',
  componentNamespace: 'Component Namespace',
  systemInstallAdminOnly: 'Only platform administrators can install platform components.',
  runtimeCluster: 'Runtime Cluster',
  defaultCluster: 'Use default cluster',
  applicationName: 'Application Name',
  applicationSlug: 'Application Slug',
  deploymentName: 'Deployment Target',
  stage: 'Stage',
  imageRef: 'Image Reference',
  imageRefHint: 'Defaults to the template image. If you use Harbor, a DockerHub proxy, or a private registry, replace it with your full image reference.',
  replicas: 'Replicas',
  cpu: 'CPU',
  memory: 'Memory',
  dataCapacity: 'Data Capacity',
  templateParameters: 'Template Parameters',
  templateParametersDescription: 'Empty auto-generated secrets are generated by the backend and written into the secret store.',
  autoGeneratePlaceholder: 'Leave empty to auto-generate',
  installNow: 'Deploy after install',
  installNowDescription: 'When disabled, the application and deployment target are created only. You can release manually from the application deployment page.',
  image: 'Image',
  officialWebsite: 'Official Website',
  officialRepository: 'Official Repository',
  port: 'Port',
  resources: 'Resources',
  categories: {
    cache: 'Cache',
    collaboration: 'Collaboration',
    cms: 'CMS',
    database: 'Database',
    databaseTool: 'Database Tool',
    developerTool: 'Developer Tool',
    lowCode: 'Low-code',
    middleware: 'Middleware',
    objectStorage: 'Object Storage',
    observability: 'Observability',
    passwordManager: 'Password Manager',
    registry: 'Registry',
    search: 'Search',
    vectorDatabase: 'Vector Database',
    webServer: 'Web Server',
  },
  stageOptions: {
    prod: 'Production',
    staging: 'Staging',
    test: 'Test',
    dev: 'Development',
  },
  valueLabels: {
    username: 'Username',
    database: 'Database',
    password: 'Password',
    rootPassword: 'Root Password',
    rpcSecret: 'RPC Secret',
    adminToken: 'Admin Token',
    metricsToken: 'Metrics Token',
    masterKey: 'Master Key',
    apiKey: 'API Key',
    mongodbUrl: 'MongoDB URL',
    dbHost: 'Database Host',
    email: 'Email',
    apiBaseUrl: 'Luna DevOps API Base URL',
    traefikMetricsUrl: 'Traefik Metrics URL',
  },
  valueHints: {
    apiBaseUrl: 'Enter the platform base URL reachable from the probe, for example https://luna-devops.example.com. Do not enter a concrete path such as /api/v1/billing/gateway-traffic; the probe appends the reporting endpoint automatically.',
    traefikMetricsUrl: 'Enter the Traefik Prometheus metrics endpoint reachable from the probe Pod. Leave blank to use http://traefik.<Gateway namespace>.svc.cluster.local:9100/metrics.',
  },
  valuePlaceholders: {
    apiBaseUrl: 'https://luna-devops.example.com',
    traefikMetricsUrl: 'http://traefik.kube-system.svc.cluster.local:9100/metrics',
  },
  templates: {
    'luna-gateway-traffic-probe': {
      description: 'Optional platform component that collects Gateway API traffic windows and reports them to billing.',
    },
    'redis': {
      description: 'In-memory data store for cache, queues, and lightweight coordination.',
    },
    'postgresql': {
      description: 'Relational database for application data, metadata, and transactional workloads.',
    },
    'mysql': {
      description: 'Classic relational database with a simple single-container setup.',
    },
    'mongodb': {
      description: 'Document database for JSON-like application data and flexible schemas.',
    },
    'mariadb': {
      description: 'MySQL-compatible relational database with a lightweight single-container setup.',
    },
    'valkey': {
      description: 'Redis-compatible in-memory data store for cache and lightweight queues.',
    },
    'memcached': {
      description: 'Tiny memory cache service for simple high-speed key-value caching.',
    },
    'rabbitmq': {
      description: 'Message broker for asynchronous jobs, events, and lightweight queues.',
    },
    'meilisearch': {
      description: 'Lightweight full-text search engine for application search and indexing.',
    },
    'grafana': {
      description: 'Metrics dashboard and visualization platform for observability data.',
    },
    'prometheus': {
      description: 'Time-series metrics database and scraping engine for observability pipelines.',
    },
    'uptime-kuma': {
      description: 'Self-hosted uptime monitor for websites, APIs, and internal services.',
    },
    'memos': {
      description: 'Lightweight self-hosted notes and knowledge snippets for small teams.',
    },
    'it-tools': {
      description: 'Handy browser-based utility toolbox for developers and operators.',
    },
    'excalidraw': {
      description: 'Simple whiteboard for diagrams, sketches, and product notes.',
    },
    'verdaccio': {
      description: 'Private npm-compatible package registry for internal JavaScript packages.',
    },
    'docker-registry': {
      description: 'Private OCI image registry for internal container image distribution.',
    },
    'pgadmin4': {
      description: 'Web management console for PostgreSQL servers and databases.',
    },
    'bytebase': {
      description: 'Database schema change and review workflow for small engineering teams.',
    },
    'garage': {
      description: 'Lightweight S3-compatible object storage for project files and artifacts.',
    },
    'nats': {
      description: 'Lightweight messaging system for events, pub/sub, and service communication.',
    },
    'clickhouse': {
      description: 'Column-oriented analytics database for logs, events, and real-time reporting.',
    },
    'qdrant': {
      description: 'Vector database for semantic search, recommendations, and AI retrieval workloads.',
    },
    'typesense': {
      description: 'Fast typo-tolerant search engine for product search and application search.',
    },
    'adminer': {
      description: 'Small web database administration tool for MySQL, PostgreSQL, SQLite, and more.',
    },
    'mongo-express': {
      description: 'Web administration interface for MongoDB databases.',
    },
    'caddy': {
      description: 'Simple web server and reverse proxy starter with a minimal static response.',
    },
    'gitea': {
      description: 'Lightweight self-hosted Git service for repositories, issues, and releases.',
    },
    'vaultwarden': {
      description: 'Lightweight self-hosted password manager compatible with Bitwarden clients.',
    },
    'nocodb': {
      description: 'Open-source no-code database interface for small internal tools and data apps.',
    },
    'wiki-js': {
      description: 'Modern self-hosted wiki for team documentation and knowledge bases.',
    },
    'wordpress': {
      description: 'Popular self-hosted CMS and blog platform; connect it to an existing MySQL-compatible database.',
    },
  },
}

export default appTemplatesPage
