apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "liteyuki-devops.workerName" . }}
  labels:
    {{- include "liteyuki-devops.componentLabels" (dict "root" . "component" "worker") | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "liteyuki-devops.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "liteyuki-devops.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
        {{- with .Values.worker.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.worker.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "liteyuki-devops.serviceAccountName" . }}
      automountServiceAccountToken: false
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          image: "{{ .Values.worker.image.repository }}:{{ include "liteyuki-devops.imageTag" (dict "Chart" .Chart "tag" .Values.worker.image.tag) }}"
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{- if .Values.metrics.enabled }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.worker.port }}
              protocol: TCP
          {{- end }}
          env:
            {{- include "liteyuki-devops.commonEnv" . | nindent 12 }}
            - name: METRICS_ADDR
              value: {{ .Values.metrics.worker.addr | quote }}
          envFrom:
            - configMapRef:
                name: {{ include "liteyuki-devops.fullname" . }}-config
          {{- with .Values.worker.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.worker.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.worker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
